### ISSUE TITLE
Develop Cluster Aware MI Monitoring Dashboard

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/micro-integrator#1997]
**Description:**
The following are the identified requirements for the dashboard.

1. Identify the nodes a particular artifact is deployed
2. Each node's status and basic runtime information
3. Option to filter artifacts by the node it is deployed on.
4. Nodes read only view (activate, deactivate)
5. Monitor set of nodes 
        - Clustered 
        - Standalone
        - Grouped view 

**Tasks**

1. Develop initial project structure
    - [x] Develop initial project structure
    - [x] Generate rest api automatically using swagger
    - [x] Create distribution

1. Identify initial ui components
    -  Table
       - [x]  Table
       - [ ] Pagination
       - [x] Sorting
       - [ ] SearchBar
       - [x] Side Navigation
       - [ ] Column Filter

   -  Side Navigation
       - [x] Copy to clipboard
       - [x] SourceView
       - [x] Toggle

   - Node Filter
       - [ ]  FIlter

**Comment by dulanjalidilmi** [comment]
This is the initial architecture diagram.

![ArchitectureDiagram](https://user-images.githubusercontent.com/38608578/97273012-c23e8d00-1858-11eb-87d3-9bb6420eec41.png)

Initially, the nodes register by sending the initial heartbeat signal to the dashboard server with the corresponding cluster id or group id notifying about its existence. Then the nodes periodically send heartbeat signals to the server notifying about their existence. Furthermore, nodes will notify the dashboard server on changes such as artifact deployment, deletion, update, etc. 

The dashboard server fetches data when it 
- receive an initial heartbeat signal from a node
- receive a node change notification
- could not find node details from the database

The dashboard server fetches node details from relevant nodes and updates the configurable DB and renders the data retrieved from the database. Once the database server does not receive heartbeats from a particular node, the dashboard server would delete the node details from the database assuming the respective node has shutdown.

**Comment by dulanjalidilmi** [comment]
The following is the modified architecture diagram. 
![ArchitectureDiagram](https://user-images.githubusercontent.com/38608578/97833586-bf7de500-1cfb-11eb-8a75-2f3f8f00d50c.jpg)

Initially, the nodes register by sending the initial heartbeat signal to the dashboard server with the corresponding cluster id or group id notifying about its existence. Then the nodes periodically send heartbeat signals to the server notifying about their existence. 

The nodes will notify the dashboard server on changes such as artifact deployment, deletion, update, etc. These changes will be added to a queue and notify the dashboard in the order. Once the dashboard server received this notification, it would send back an acknowledgment to the node. If the node does not receive an ack, it would resend notifications with a backoff period until it receives an ack.  

The dashboard server fetches data when it 
- receive an initial heartbeat signal from a node
- receive a node change notification
- could not find node details from the database
- the user selected sync option (This is available as a troubleshoot option)

The dashboard server fetches node details from relevant nodes and updates the configurable DB and renders the data retrieved from the database. Once the database server does not receive heartbeats from a particular node, the dashboard server would delete the node details from the database assuming the respective node has shutdown.

Sync option is available under the settings section for the user to select the set of nodes to synchronize. This is available as a troubleshooting option to sync in scenarios such as a network failure.
