### ISSUE TITLE
Improve the User experience of the Inegrator Dashboard

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#2394]
**Description:**
This is a high level task to improve UX of the dashboard. Following are the sub tasks that are to be carried out.

- [ ] https://github.com/wso2/micro-integrator/issues/2214
- [ ] https://github.com/wso2/micro-integrator/issues/2177
- [x] https://github.com/wso2/micro-integrator/issues/2392
- [x] https://github.com/wso2/micro-integrator/issues/2393
- [ ] https://github.com/wso2/micro-integrator/issues/2395
- [ ] https://github.com/wso2/micro-integrator/issues/2396
- [ ] https://github.com/wso2/micro-integrator/issues/2507

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
