### ISSUE TITLE
Expose proxy services via service Catalog

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#2397]
**Description:**
Currently, only Rest APIs are shown Service Catalog. This task is to expose proxy services to the Service Catalog as Passthrough SOAP endpoint.

The suggested approach for implementing this feature includes the following subtasks.

- [x] https://github.com/wso2/integration-studio/issues/882
- [x] #2414
- [x] https://github.com/wso2/product-apim/issues/11656
- [x] https://github.com/wso2/product-apim/issues/11746
- [x] https://github.com/wso2/docs-apim/issues/4727
- [ ] https://github.com/wso2/product-apim/issues/11744

**Affected Product Version:**
APIM 4.1.0
MI 4.1.0
Integration Studio 8.1.0

**Comment by sajithaliyanage** [comment]
Issue: https://github.com/wso2/integration-studio/issues/888 needs to be addressed along with this feature for migrating users.

**Comment by nandika** [comment]
Only UI tests is pending as UI test framework is under development.
