### ISSUE TITLE
Fix Dashboard 4.2.0 issues

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/micro-integrator#3136]
### Problem

Following issues are reported on WSO2 Monitoring Dashboard

- [x] User list limited by 1500 entries  - https://github.com/wso2/api-manager/issues/1674
- [x] Page Reload issue - https://github.com/wso2/api-manager/issues/1717
- [x] Faulty CAR Files are not listed in the Dashboard or over the CLI - https://github.com/wso2/api-manager/issues/1662
- [x] Unable to override the authorization endpoint when configuring SSO for MI dashboard - https://github.com/wso2/api-manager/issues/1525
- [x]  Authorization for other Management API resources does not work in MI-Dashboard  - https://github.com/wso2/api-manager/issues/1593

### Affected Component

MIDashboard

### Version

4.x.x
