### ISSUE TITLE
Enable ws-security related testcases

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#3170]
### Description

Currently ws-security testcases are disabled. The task is to enable these testcases, in order to verify ws-security related usecases.

- [x] wso2/api-manager#1066
- [x] wso2/api-manager#1067
- [x] wso2/api-manager#1149
- [ ] wso2/docs-apim#6776
- [ ] wso2/api-manager#1151

### Affected Component

MI
