### ISSUE TITLE
Support WebSocket and HTTP transports on the same ports

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#3181]
**Description:**

Currently, the WebSocket and the HTTP requests are handled on different ports in the Synapse runtime. However, by design, WebSocket connections and HTTP connections can be handled on the same port as the WebSocket handshake starts with an HTTP request/response. Therefore, we need to support WebSocket and HTTP transports on the same ports to avoid any additional work from the client-side and to be aligned with the API Microgateway (as API Microgateway already supports WebSocket and HTTP transports on the same ports).

**Describe your solution**

The suggested approach for implementing this feature involves the following subtasks.

- [x] wso2/micro-integrator#2444
- [x] wso2/micro-integrator#2445
- [x] wso2/micro-integrator#2446
- [x] wso2/micro-integrator#2447
- [x] wso2/micro-integrator#2448
- [x] wso2/micro-integrator#2474
- [x] wso2/micro-integrator#2530
- [x] wso2/api-manager#382
- [x] wso2/api-manager#383
- [ ] wso2/api-manager#422
- [ ] wso2/api-manager#423
- [ ] wso2/api-manager#424
- [ ] wso2/api-manager#425
- [ ] wso2/api-manager#426
- [ ] wso2/api-manager#427
- [x] wso2/micro-integrator#2591
- [x] wso2/micro-integrator#2595
- [x] wso2/micro-integrator#2589
- [x] wso2/micro-integrator#2590
- [ ] wso2/api-manager#428

Post feature tasks

- [x] wso2/micro-integrator#2449
- [ ] wso2/api-manager#429
